name: conformance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conformance-test:
    name: conformance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test
        working-directory: conformance
        run: cargo test
