name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hickory_changed:
    name: determine if hickory-dns source was modified
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.output_step.outputs.outcome}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: output_step
        run: |
          git diff --name-only origin/${{github.base_ref}} HEAD | grep -v '^conformance/' && echo "outcome=1" >> "$GITHUB_OUTPUT" || echo "outcome=0" >> "$GITHUB_OUTPUT"

  main-test:
    name: unit and integration tests
    needs: hickory_changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        # runs conditionally
      - name: cargo test
        if: needs.hickory_changed.outputs.outcome == '1'
        run: cargo test

  # always runs
  conformance-test:
    name: conformance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test
        working-directory: conformance
        run: cargo test
